name: CI/CD
on:
  push:
    branches:
      - backend
    jobs:
      backend:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
          uses: actions/checkout@v3
          - name: Build backend
          run: go build -o backend/cmd/main backend/cmd/main.go